package mvc.vista;

import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuItem;

/**
 *
 * @author PCX
 */
public class Ventana_Principal extends javax.swing.JFrame {

    /**
     * Creates new form Ventana_Principal
     */
    public Ventana_Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jToolBar1 = new javax.swing.JToolBar();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btn_mantenimiento = new javax.swing.JButton();
        btn_generarReporte = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jButton4 = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        jButton2 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jComboBox1 = new javax.swing.JComboBox<>();
        dsk_escritorio = new javax.swing.JDesktopPane();
        lbl_mensajes = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Menu_personas = new javax.swing.JMenu();
        Sub_mantenimiento = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToolBar1.setRollover(true);
        jToolBar1.add(jSeparator2);

        btn_mantenimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mvc/vista/iconos/user-detail-solid-24.png"))); // NOI18N
        btn_mantenimiento.setToolTipText("Mantenimiento de Personas");
        btn_mantenimiento.setFocusable(false);
        btn_mantenimiento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_mantenimiento.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_mantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mantenimientoActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_mantenimiento);

        btn_generarReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mvc/vista/iconos/report-solid-24.png"))); // NOI18N
        btn_generarReporte.setToolTipText("Generar Reporte");
        btn_generarReporte.setFocusable(false);
        btn_generarReporte.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_generarReporte.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btn_generarReporte);
        jToolBar1.add(jSeparator4);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mvc/vista/iconos/save-solid-24.png"))); // NOI18N
        jButton4.setToolTipText("Guardar Cambios");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton4);
        jToolBar1.add(jSeparator5);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mvc/vista/iconos/printer-solid-24.png"))); // NOI18N
        jButton2.setToolTipText("Imprimir");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton2);
        jToolBar1.add(jSeparator3);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Seleccionar>", "Enviar Catalogo Correo", "Enviar Catalogo Grupo" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jComboBox1);

        getContentPane().add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 40));

        javax.swing.GroupLayout dsk_escritorioLayout = new javax.swing.GroupLayout(dsk_escritorio);
        dsk_escritorio.setLayout(dsk_escritorioLayout);
        dsk_escritorioLayout.setHorizontalGroup(
            dsk_escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1270, Short.MAX_VALUE)
        );
        dsk_escritorioLayout.setVerticalGroup(
            dsk_escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        getContentPane().add(dsk_escritorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1270, 540));

        lbl_mensajes.setBackground(new java.awt.Color(204, 102, 0));
        lbl_mensajes.setForeground(new java.awt.Color(153, 153, 0));
        lbl_mensajes.setText("1.0");
        getContentPane().add(lbl_mensajes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 590, 1270, 20));

        Menu_personas.setText("Personas");

        Sub_mantenimiento.setText("Menu de Personas");
        Sub_mantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sub_mantenimientoActionPerformed(evt);
            }
        });
        Menu_personas.add(Sub_mantenimiento);

        jMenuItem2.setText("Reporte de Personas");
        Menu_personas.add(jMenuItem2);
        Menu_personas.add(jSeparator1);

        jMenuItem3.setText("Salida");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        Menu_personas.add(jMenuItem3);

        jMenuBar1.add(Menu_personas);

        jMenu2.setText("Reportes");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Sub_mantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sub_mantenimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sub_mantenimientoActionPerformed

    public JMenu getMenu_personas() {
        return Menu_personas;
    }

    public void setMenu_personas(JMenu Menu_personas) {
        this.Menu_personas = Menu_personas;
    }

    public JMenuItem getSub_mantenimiento() {
        return Sub_mantenimiento;
    }

    public void setSub_mantenimiento(JMenuItem Sub_mantenimiento) {
        this.Sub_mantenimiento = Sub_mantenimiento;
    }

    public JButton getBtn_mantenimiento() {
        return btn_mantenimiento;
    }

    public void setBtn_mantenimiento(JButton btn_mantenimiento) {
        this.btn_mantenimiento = btn_mantenimiento;
    }

    public JMenu getjMenu2() {
        return jMenu2;
    }

    public void setjMenu2(JMenu jMenu2) {
        this.jMenu2 = jMenu2;
    }

    public JLabel getLbl_mensajes() {
        return lbl_mensajes;
    }

    public void setLbl_mensajes(JLabel lbl_mensajes) {
        this.lbl_mensajes = lbl_mensajes;
    }

    public JDesktopPane getDsk_escritorio() {
        return dsk_escritorio;
    }

    public void setDsk_escritorio(JDesktopPane dsk_escritorio) {
        this.dsk_escritorio = dsk_escritorio;
    }

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void btn_mantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mantenimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_mantenimientoActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    public JButton getBtn_generarReporte() {
        return btn_generarReporte;
    }

    public void setBtn_generarReporte(JButton btn_generarReporte) {
        this.btn_generarReporte = btn_generarReporte;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Menu_personas;
    private javax.swing.JMenuItem Sub_mantenimiento;
    private javax.swing.JButton btn_generarReporte;
    private javax.swing.JButton btn_mantenimiento;
    private javax.swing.JDesktopPane dsk_escritorio;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lbl_mensajes;
    // End of variables declaration//GEN-END:variables
}
